fastiv
======

'fastiv' is a fast image viewer, supporting BMP, PNG, GIF, JPEG, and optionally
RAW pictures.

It is meant to be a viable replacement for Eye of GNOME, which is slow, likes
to break on huge pictures, and its underlying gdk-pixbuf can only be made to use
the broken libopenraw
https://mail.gnome.org/archives/eog-list/2016-January/msg00004.html[as of now].

Further development
-------------------
Urgent blockers for the first stable version:

 - directory browsing
 - implement zoom and scrolling

High priority:

 - some level of asynchronous loading and preloading,
   which becomes a difficult problem with network mounts,
   confusingly acting as fast devices
 - write a replacement for GNOME's Nautilus in grid mode:
   read-only, with focus on staggered previews and minimising wasted space

Low priority:

 - display 16-bit pictures smoothly, using the 30-bit depth under X.org
 - make RAW as fast as it can possibly be
 - load everything that resembles a picture, potentially even play video
 - port to something less hostile than the current GNOME stack, such as SDL,
   although it may involve a lot of reimplemented code,
   or result in reduced functionality

Non-goals:

 - fancy UI, focus solely on speed of use
 - memory efficiency, though preloading can cause some pressure

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR.

Building and Running
--------------------
Build dependencies: Meson, pkg-config +
Runtime dependencies: gtk+-3.0, libturbojpeg, LibRaw (optional),
shared-mime-info

 $ git clone --recursive https://git.janouch.name/p/fastiv.git
 $ meson builddir
 $ cd builddir
 $ meson compile

To install the application, you can do:

 # meson install

Contributing and Support
------------------------
Use https://git.janouch.name/p/fastiv to report any bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
