fastiv
======

'fastiv' is a fast image viewer, directly supporting BMP, PNG, GIF, JPEG, WebP,
and optionally raw photos, HEIC, AVIF, SVG, X11 cursors and TIFF,
or whatever gdk-pixbuf loads.

Its development status can be summarized as '`beta`'.
E.g., certain GIFs animate wrong.

Non-goals
---------
 - fancy UI--the focus is on speed of use first, colour accuracy second
 - editing--that's what _editors_ are for, be it GIMP or Rawtherapee;
   nothing beyond the most basic of adjustments is desired
 - memory efficiency, though preloading can cause some pressure
 - portability to non-UNIXy systems

Packages
--------
Regular releases are sporadic.  git master should be stable enough.  You can get
a package with the latest development version from Archlinux's AUR.

Building and Running
--------------------
Build dependencies: Meson, pkg-config +
Runtime dependencies: gtk+-3.0, glib>=2.64, pixman-1, shared-mime-info,
libturbojpeg, libwebp, spng>=0.7.0 +
Optional dependencies: lcms2, LibRaw, librsvg-2.0, xcursor, libheif, libtiff,
gdk-pixbuf-2.0, ExifTool

 $ git clone --recursive https://git.janouch.name/p/fastiv.git
 $ meson builddir
 $ cd builddir
 $ meson compile

To install the application, you can do:

 # meson install

Configuration
-------------
The standard means to adjust the looks of the program is through GTK+ 3 CSS.
As an example, to tightly pack browser items, put the following in your
_~/.config/gtk-3.0/gtk.css_:

 fiv-browser { -FivBrowser-spacing: 0; padding: 0; border: 0; margin: 0; }

The GTK+ inspector will be very helpful, should you want to experiment.

Contributing and Support
------------------------
Use https://git.janouch.name/p/fastiv to report any bugs, request features,
or submit pull requests.  `git send-email` is tolerated.  If you want to discuss
the project, feel free to join me at ircs://irc.janouch.name, channel #dev.

Bitcoin donations are accepted at: 12r5uEWEgcHC46xd64tt3hHt9EUvYYDHe9

License
-------
This software is released under the terms of the 0BSD license, the text of which
is included within the package along with the list of authors.
